accumulate: 1
batch_size: 512
bottleneck: false
classify: true
dropout_rate: 0.5
lr: 0.01
lr_scheduler: step
model: wide_resnet101_2
n_partitions: 1
n_steps: 2
optimizer: adamw
seed: 1111
simple_clf: true
step: 1024
step_factor: 0.1
step_size: 4
swa_anneal: 8
swa_start: 120
tgt_tax_lvl: phylum
window: 1024
